# Generated by Django 4.2.2 on 2023-07-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('examapp', '0004_rename_customuser_customusermodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserModel',
            new_name='CustomUser',
        ),
        migrations.RenameModel(
            old_name='GroupModel',
            new_name='Group',
        ),
    ]
