# Generated by Django 4.2.2 on 2023-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0009_answer_question_customuser_photo_school_group_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='examapp.answer'),
        ),
    ]
