# Generated by Django 4.2.2 on 2023-07-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0011_ministry_subject_variant_question_number_region_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=240)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.group')),
                ('variants', models.ManyToManyField(to='examapp.variant')),
            ],
        ),
    ]
