# Generated by Django 4.2.2 on 2023-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0013_alter_examforgroup_ends_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('AH', 'Area Head'), ('MH', 'Ministry Head'), ('RH', 'Region Head'), ('PU', 'Pupil'), ('PA', 'Parent'), ('SD', 'School Director'), ('SS', 'School Staff'), ('TE', 'Teacher')], max_length=20, null=True),
        ),
    ]
