# Generated by Django 4.2.2 on 2023-07-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0014_alter_customuser_options_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('AH', 'Area Head'), ('MH', 'Ministry Head'), ('RH', 'Region Head'), ('PU', 'Pupil'), ('PA', 'Parent'), ('SD', 'School Director'), ('SS', 'School Staff'), ('TE', 'Teacher')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
