# Generated by Django 4.2.2 on 2023-07-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0017_rename_currenttest_currentexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='examapp.subject')),
                ('second_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='examapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='currentexam',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.subjectcombination'),
        ),
        migrations.AddField(
            model_name='result',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.subjectcombination'),
        ),
    ]
