# Generated by Django 4.2.2 on 2023-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0019_alter_result_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
