# Generated by Django 4.2.2 on 2023-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0020_subject_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentexam',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('AH', 'Area Head'), ('MH', 'Ministry Head'), ('RH', 'Region Head'), ('PU', 'Pupil'), ('PA', 'Parent'), ('SD', 'School Director'), ('SS', 'School Staff'), ('TE', 'Teacher'), ('MO', 'Moderator')], max_length=20),
        ),
        migrations.AddField(
            model_name='currentexam',
            name='subjects',
            field=models.ManyToManyField(to='examapp.subject'),
        ),
    ]
