# Generated by Django 4.2.2 on 2023-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0022_question_points_pupilanswer_result_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='pupilanswer',
            name='answer',
            field=models.ManyToManyField(to='examapp.answer'),
        ),
    ]
