# Generated by Django 4.2.2 on 2023-07-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0023_remove_pupilanswer_answer_pupilanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupilanswer',
            old_name='answer',
            new_name='answers',
        ),
    ]
