# Generated by Django 4.2.2 on 2023-07-12 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0027_remove_result_subjects_result_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='examforgroup',
            name='ended_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
