# Generated by Django 4.2.2 on 2023-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0030_alter_examforgroup_ended_users_alter_result_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilanswer',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
