# Generated by Django 4.2.2 on 2023-07-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0031_pupilanswer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.area'),
        ),
    ]
