# Generated by Django 4.2.2 on 2023-07-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0032_school_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examapp.area'),
            preserve_default=False,
        ),
    ]
