# Generated by Django 4.2.2 on 2023-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0035_result_is_violated'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='language',
            field=models.CharField(choices=[('KAZ', 'KAZ'), ('RUS', 'RUS')], default='Rus', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='exam_type',
            field=models.CharField(choices=[('ENT', 'ENT'), ('MODO', 'MODO')], max_length=10),
        ),
    ]
