# Generated by Django 4.2.2 on 2023-08-28 22:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0037_remove_variant_exam_type_remove_variant_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'subject Translation',
                'db_table': 'examapp_subject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases = (parler.models.TranslatableModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='variant',
            name='exam_type',
            field=models.CharField(choices=[('MODO', 'MODO'), ('ENT', 'ENT')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='language',
            field=models.CharField(choices=[('KAZ', 'KAZ'), ('RUS', 'RUS')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariantTranslation',
        ),
        migrations.AddField(
            model_name='subjecttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='examapp.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjecttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
