# Generated by Django 4.2.2 on 2023-09-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0038_subjecttranslation_remove_subject_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='group',
            field=models.CharField(choices=[(4, 4), (9, 9)], default=9, max_length=2),
            preserve_default=False,
        ),
    ]
