version: "3.9"
services:
  web:
    build: .
    expose:
      - 8000
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 2
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - web
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - redis
      - web

volumes:
  static_volume:
  media_volume: